In [1]:
import numpy as np

In [7]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [8]:
b = 5
print(a+b)

[[ 6  7  8]
 [ 9 10 11]]


In [11]:
c = np.array([2])
print(c.shape)
print(a+c)

(1,)
[[3 4 5]
 [6 7 8]]
